/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo = () => {
  return (
    <img
      src="https://cdn.builder.io/api/v1/image/assets%2F013dbc85a35a4f2ea2d2664ea6761da6%2Fc86d3568a25644c99bb1de6716ee1dac"
      alt="Seamless Research Logo"
      className="box-border object-contain overflow-hidden shrink-0 mx-auto w-full max-h-12 aspect-square max-w-[89px] min-h-[20px] min-w-[20px] max-md:grow max-md:mr-auto max-md:w-auto max-sm:mr-auto max-sm:max-h-[42px] max-sm:max-w-[53px] max-sm:min-w-[42px]"
    />
  );
};

export default Logo;
