/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Navigation = () => {
  return (
    <nav className="flex relative flex-row mt-px ml-auto w-auto grow-0 max-md:hidden max-sm:hidden">
      <div className="box-border flex relative flex-col shrink-0 my-auto w-0.5 h-8 bg-stone-300" />
      <div className="flex relative flex-row gap-4 ml-4">
        <button className="box-border relative shrink-0 p-3 text-center text-white rounded appearance-none cursor-pointer grow-0">
          About Us
        </button>
        <button className="box-border relative shrink-0 p-3 text-center rounded appearance-none cursor-pointer bg-neutral-700 grow-0 text-[white]">
          Help
        </button>
      </div>
    </nav>
  );
};

export default Navigation;
