/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";

const SeamlessResearch = () => {

  return (
    <div className="box-border flex relative flex-col shrink-0 px-5 py-2 h-auto shadow-sm bg-neutral-900 grow-0">
      <section className="box-border flex relative flex-col grow shrink-0 self-stretch px-5 py-2 mx-auto w-full h-auto shadow-sm bg-neutral-900 max-w-[1200px]">
        <Header />
        <img
          src="https://cdn.builder.io/api/v1/image/assets%2FYJIGb4i01jvw0SRdL5Bt%2F0663bd40b99a4259a807f6f0014df73d"
          alt=""
          className="box-border object-cover overflow-hidden shrink-0 mt-5 w-full aspect-[3.87] min-h-[20px] min-w-[20px] max-md:flex max-md:w-6 max-md:h-6 max-md:max-w-[48px] max-sm:flex max-sm:ml-auto max-sm:w-6 max-sm:h-6"
        />
      </section>
    </div>
  );
};

export default SeamlessResearch;
