/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FormInput({ label, id, type = "text", placeholder, value }) {
  return (
    <div className="mb-7">
      <label
        htmlFor={id}
        className="block mb-2 text-sm font-semibold leading-5 text-gray-700"
      >
        {label}:
      </label>
      <input
        type={type}
        id={id}
        name={id}
        placeholder={placeholder}
        value={value}
        className="w-full px-5 py-4 text-sm font-medium leading-5 bg-white rounded-lg border border-gray-300 border-solid shadow-md text-stone-300"
        readOnly
      />
    </div>
  );
}

export default FormInput;
