/**
 * This code was generated by Builder.io.
 */
import React from "react";

function FormSelect({ label, id, options, defaultValue }) {
  return (
    <div className="mb-7">
      <label
        htmlFor={id}
        className="block mb-2 text-sm font-medium leading-5 text-gray-700"
      >
        {label}:
      </label>
      <div className="relative">
        <select
          id={id}
          name={id}
          defaultValue={defaultValue}
          className="w-full px-5 py-4 text-sm font-medium leading-5 bg-white rounded-lg border border-gray-300 border-solid shadow-md text-stone-300 appearance-none"
        >
          {options.map((option) => (
            <option key={option.value} value={option.value}>
              {option.name}
            </option>
          ))}
        </select>
        <div className="absolute inset-y-0 right-0 flex items-center px-2 pointer-events-none">
          <svg className="w-4 h-4 fill-current" viewBox="0 0 20 20">
            <path
              d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
              clipRule="evenodd"
              fillRule="evenodd"
            ></path>
          </svg>
        </div>
      </div>
    </div>
  );
}

export default FormSelect;
